version: '3'
services:
  registry:
    image: registry:2
    container_name: registry
    ports:
      - "5000:5000"
    volumes:
      - ./data:/var/lib/registry
  registry-frontend:
    image: konradkleine/docker-registry-frontend:v2
    container_name: registry-frontend
    ports:
      - "8080:80"
    environment:
      - ENV_DOCKER_REGISTRY_HOST=registry
      - ENV_DOCKER_REGISTRY_PORT=5000
    depends_on:
      - registry
