apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: jenkins
spec:
  type: NodePort
  selector:
    app: jenkins
  ports:
    - port: 8080        # Service port
      targetPort: 8080  # Container port
      nodePort: 30080   # NodePort must have capital 'P'
