apiVersion: v1
kind: Pod
metadata:
  name: secret-env-demo
spec:
  containers:
  - name: app
    image: busybox
    command: ["sh", "-c", "env; sleep 3600"]
    env:
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: my -secret
          key: username
    - name: DB_PASS
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: password
