apiVersion: v1
kind: Pod
metadata:
  name: configmap-env-demo
spec:
  containers:
  - name: cont-po_confg
    image: busybox
    command: ["sh", "-c", "env; sleep 3600"]
    env: 
    - name: APP_MODE
    valueFrom:
      configMapKeyRef:
          name: my-config
          key: APP_MODE
