apiVersion: v1
kind: Pod
metadata:
  name: hostpathdir-vol
spec:
  containers:
  - name: app
    image: busybox
    command: ["sh", "-c", "ls /host; Sleep 3600"]
    volumeMounts: 
    - name: host-volume
      mountPath: /host
  volumes:
  - name: host-volume
    hostPath:
      path: /etc  #host path - Only used for testing/dev; not recommended in production (node-specific)
      
