apiVersion: v1
kind: Pod
metadata: 
  name: pvc-test-pod
spec:
  containers:
  - name: app
    image: busybox
    command: ["sh", "-c", "echo hello PV > /data/output.txt; sleep 3600"]
    volumeMounts:
    - name: pvc-storage
      mountPath: "/data"
  volumes:
  - name: pvc-storage
    persistentVolumeClaim:
      claimName: my-pvc
