apiVersion: v1
kind: Pod
metadata:
  name: secret-vol-demo
spec:
  containers:
  - name: mybusyapp
    image: busybox
    command: ["sh", "-c", "cat /etc/secret-volume/username; sleep 3600"]
    volumeMounts: 
    - name: secret-vol
      mountPath: "/etc/secret-volume"
      readOnly: true
  volumes:
  - name: secret-vol
    secretName: my-secret
    
  
