version: "3.8"
services:
  frontend:
    image: my-frontend
    ports:
      - "8082:80"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
       
  backend:
    image: my-backend
    ports:
      - "5000:5000"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
