version: “3.8”
services:
     web:
            image: nginx
            ports:
                -  “80:80”
            deploy:
                  replicas: 3
                  restart_policy:
                        condition: on-failure
